name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Node.js and dependencies
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use the version of Node.js that your app requires

      - name: Install dependencies
        run: npm install

      # Build the Next.js app
      - name: Build the app
        run: npm run build

      # Deploy to Vercel
      - name: Deploy to Vercel
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
